exports.seed = function(knex, Promise) {
return knex('presprops').del()
.then(function () {
return Promise.all([
knex('presprops').insert({title: 'Beacon Hill 2Bed Penthouse w/Private Deck – OFF-MARKET Opportunity to BUY', price: '$699,000.00', bedrooms: '2' ,bathrooms: '1' , type: 'Condominium' , status: 'For Sale' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/08/72a8bha-427x600.jpg' }),
knex('presprops').insert({title: 'Beacon Hill Renovated 1Bedroom Plus Available Sept 15 OR October 1', price: '$2,250.00', bedrooms: '1.5' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/08/892A-1.jpg' }),
knex('presprops').insert({title: 'Back Bay Renovated LARGE 2Bed 2Bath Available 9/1', price: '$3,200.00', bedrooms: '2' ,bathrooms: '2' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/08/401stb2a.jpg' }),
knex('presprops').insert({title: 'Beacon Hill Large 2Bed Duplex Condo for Rent Available September 1', price: '$2,800.00', bedrooms: '2' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/08/93JBHA.jpg' }),
knex('presprops').insert({title: 'North End 2 Bedroom Available September 1', price: '$2,300.00', bedrooms: '2' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/07/611enea.jpg' }),
knex('presprops').insert({title: 'BRAND NEW Back Bay 1 Bedroom Duplex for Rent', price: '$3,100.00', bedrooms: '1' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/07/721gbva-427x600.jpg' }),
knex('presprops').insert({title: 'Beacon Hill Pet Friendly Studio Available September 1', price: '$1,875.00', bedrooms: '1' ,bathrooms: 'Apartment' , type: 'For Rent' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/07/1412abha.jpg' }),
knex('presprops').insert({title: '*NO BROKER FEE* Back Bay 1 Bedroom On Newbury Street Available September 1', price: '$2,700.00', bedrooms: '1' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/7223nbbb.jpg' }),
knex('presprops').insert({title: '*NO BROKER FEE* Back Bay Pet Friendly 1 Bedroom Available September 1', price: '$2,225.00', bedrooms: '1' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/07/5224rnbba.jpg' }),
knex('presprops').insert({title: '*NO BROKER FEE* Back Bay 1 Bedroom Available September 1', price: '$2,075.00', bedrooms: '1' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/5223fnbba.jpg' }),
knex('presprops').insert({title: '*HALF BROKER FEE* Pet Friendly Studio Available September 1', price: '$1,925.00', bedrooms: '1' ,bathrooms: 'Apartment' , type: 'For Rent' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/425jbha.jpg' }),
knex('presprops').insert({title: '*HALF BROKER FEE* Back Bay 1 Bedroom Available NOW', price: '$2,375.00', bedrooms: '1' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/5915cbbg.jpg' }),
knex('presprops').insert({title: 'Fenway 1 Bedroom Available September 1', price: '$2,500.00', bedrooms: '1' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/001306jfa.jpg' }),
knex('presprops').insert({title: 'Front Facing Studio Available September 1- Rooming House!', price: '$1,035.00', bedrooms: '1' ,bathrooms: 'Rooming House' , type: 'For Rent' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/213fbha-3.jpg' }),
knex('presprops').insert({title: '2 Room Studio Available September 1- Rooming House', price: '$1,000.00', bedrooms: '1' ,bathrooms: 'Rooming House' , type: 'For Rent' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/213fbha.jpg' }),
knex('presprops').insert({title: 'Beacon Hill LARGE 3 Bedroom Available September 1', price: '$3,900.00', bedrooms: '3' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/16m1bha.jpg' }),
knex('presprops').insert({title: 'Back Bay 2Bed/1.5 Bath Available September 1', price: '$3,650.00', bedrooms: '2' ,bathrooms: '1.5' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/06/8713mbba.jpg' }),
knex('presprops').insert({title: 'Back Bay 2 Bedroom Available September 1', price: '$3,395.00', bedrooms: '2' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/05/0416BBBA.jpg' }),
knex('presprops').insert({title: 'Large Back Bay 2 Bedroom Available NOW OR September 1', price: '$3,975.00', bedrooms: '2' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/08/041b2bbba.jpg' }),
knex('presprops').insert({title: 'Fully Renovated Back Bay 2BR+ w/ Private Roof Deck! Available NOW', price: '$3,950.00', bedrooms: '2' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/08/871m6bba.jpg' }),
knex('presprops').insert({title: 'Beacon Hill 3 Bedroom Available September 1', price: '$3,400.00', bedrooms: '3' ,bathrooms: '1' , type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/03/824pha.jpg' }),
knex('presprops').insert({title: 'Beautiful Back Bay 2 Bedroom Plus Duplex Available October 1', price: '$4,350.00', bedrooms: 2,bathrooms: 2.5, type: 'Apartment' , status: 'For Rent' , piclink: 'http://yourbostonapartments.com/wp-content/uploads/2016/03/2533ba.jpg' })
]);
});
};